#
# Copyright (c) 2020 Ubique Innovation AG <https://www.ubique.ch>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#

spring:
  profiles.active: ${SPRING_PROFILES_ACTIVE:radarcovid-local,jwt}
  application.name: dpppt

  sleuth:
    log.slf4j:
      enabled: true
    keys.http.headers: X-Amz-Cf-Id
    baggage:
      remote-fields: X-Amz-Cf-Id
      correlation-fields: X-Amz-Cf-Id

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_KEY:}
    region:
      auto: ${CLOUD.AWS.REGION.AUTO:false}
      static: ${CLOUD.AWS.REGION.STATIC:eu-west-1}
    stack:
      auto: ${CLOUD.AWS.STACK.AUTO:false}

management:
  endpoint.health.probes.enabled: true
  endpoints.enabled-by-default: false
  metrics:
    enable:
      all: true
    export:
      cloudwatch:
        namespace: dpppt
        batch-size: 20

server:
  error.whitelabel.enabled: true
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/plain
      - text/xml
  http2:
    enabled: true
  port: ${SERVER_PORT:8080}
  tomcat:
    mbeanregistry:
      enabled: true
  shutdown: graceful

logging:
  group:
    cleanup:
      - org.dpppt.backend.sdk.ws.config.WSRadarCovidConfig
      - org.dpppt.backend.sdk.data.gaen.JDBCGAENDataServiceImpl
      - org.dpppt.backend.sdk.data.JDBCDPPPTDataServiceImpl
      - org.dpppt.backend.sdk.data.JDBCRedeemDataServiceImpl
  level:
    root: info
    cleanup: warn
    org.springframework: warn
    org.flywaydb: warn
    com.amazonaws: error
    org.dpppt.backend.sdk.data.gaen.fakekeyservice: info
    org.dpppt.backend.sdk.ws.radarcovid: debug
    org.dpppt.backend.sdk.ws.radarcovid.annotation: info
    org.dpppt.backend.sdk.ws.radarcovid.config: info
    org.dpppt.backend.sdk.ws.security.gaen: debug
    org.dpppt.backend.sdk.ws.insertmanager.InsertManager: off
    org.dpppt: info
    com.zaxxer.hikari.pool.HikariPool: debug
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari: debug
    org.springframework.security: DEBUG
  pattern:
    console: '[%-5level] [%X{X-B3-TraceId:-},%X{X-Amz-Cf-Id:-}] - %c{1} - %msg%n'


#-------------------------------------------------------------------------------
# JDBC Config
#-------------------------------------------------------------------------------

datasource:
  url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/dpppt}
  username: ${DATASOURCE_USER:dpppt}
  password: ${DATASOURCE_PASS:dpppt}
  schema: ${DATASOURCE_SCHEMA:dpppt}
  driverClassName: org.postgresql.ds.PGSimpleDataSource
  failFast: ${DATASOURCE_FAIL_FAST:true}
  minimumIdle: ${DATASOURCE_MIN_IDLE:5}
  maximumPoolSize: ${DATASOURCE_MAX_POOL_SIZE:15}
  maxLifetime: ${DATASOURCE_MAX_LIFE_TIME:1700000}
  idleTimeout: ${DATASOURCE_IDLE_TIMEOUT:600000}
  connectionTimeout: ${DATASOURCE_CONNECTION_TIMEOUT:30000}
  flyway.load: ${DATASOURCE_FLYWAY_LOAD:true}

ws:
  exposedlist:
    cachecontrol: ${WS_EXPOSEDLIST_CACHECONTROL:300000}
    batchlength: ${WS_EXPOSEDLIST_BATCHLENGTH:7200000}
    requestTime: ${WS_EXPOSEDLIST_REQUESTTIME:1500}
  gaen:
    randomkeysenabled: ${WS_GAEN_RANDOMKEYSENABLED:false}
    randomkeyamount: ${WS_GAEN_RANDOMKEYAMOUNT:10}
  retentiondays: ${WS_RETENTIONDAYS:14}
  app:
    source: ${WS_APP_SOURCE:org.dpppt.demo}
    key_size: ${WS_APP_KEY_SIZE:32}
    ios.bundleId: ${WS_APP_IOS_BUNDLEID:org.dpppt.ios.demo}
    android.packageName: ${WS_APP_ANDROID_PACKAGENAME:org.dpppt.android.demo}
    gaen:
      keyVersion: ${WS_APP_GAEN_KEYVERSION:v1}
      keyIdentifier: ${WS_APP_GAEN_KEYIDENTIFIER:214}
      algorithm: ${WS_APP_GAEN_ALGORITHM:1.2.840.10045.4.3.2}
      region: ${WS_APP_GAEN_REGION:es}
      key_size: ${WS_APP_GAEN_KEY_SIZE:16}
    jwt:
      algorithm: ${WS_APP_JWT_ALGORITHM:EC}
      publickey: ${WS_APP_JWT_PUBLICKEY:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNDdLU0ZqSVd4RVJVc2FQQjhLMi91bkpqaXdISAo5Vk85U2NSZm0wN3BvaURyRHlCWXZkRnBlOG9IWnh4M0FyMHVvRjhGbkNWWGlwRkQ0SG1UeC9iRjdnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t}
    efgs:
      country-origin: ${WS_APP_EFGS_COUNTRY:ES}
      report-type: ${WS_APP_EFGS_REPORT_TYPE:1}
  headers:
    protected: ${WS_HEADERS_PROTECTED:X-HELLO,X-BATCH-RELEASE-TIME}
    debug: ${WS_HEADERS_DEBUG:true}
  ecdsa.credentials:
    privateKey: ${GAEN_CREDENTIALS_PRIVATE_KEY:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0lrZzRsNmdaTGNHKytRK2cKT3ZyRDNGSUNWUkxkSzRpRW9lUDRFUHEvMWtlaFJBTkNBQVRqc3BJV01oYkVSRlN4bzhId3JiKzZjbU9MQWNmMQpVNzFKeEYrYlR1bWlJT3NQSUZpOTBXbDd5Z2RuSEhjQ3ZTNmdYd1djSlZlS2tVUGdlWlBIOXNYdQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t}
    publicKey: ${GAEN_CREDENTIALS_PUBLIC_KEY:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNDdLU0ZqSVd4RVJVc2FQQjhLMi91bkpqaXdISAo5Vk85U2NSZm0wN3BvaURyRHlCWXZkRnBlOG9IWnh4M0FyMHVvRjhGbkNWWGlwRkQ0SG1UeC9iRjdnPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t}

application:
  endpoint:
    validation:
      url: ${TAN_VALIDATION_URL:}
      enabled: ${TAN_VALIDATION_ENABLED:false}
  response:
    retention:
      enabled: ${RESPONSE_RETENTION_ENABLED:true}
      time:
        exposed: ${RESPONSE_RETENTION_TIME_EXPOSED:1000} # milliseconds
        exposednextday: ${RESPONSE_RETENTION_TIME_EXPOSEDNEXTDAY:1000} # milliseconds
  log:
    enabled: ${LOGGABLE_ENABLED:false}

