version: '3.8'

services:

  dpppt:
    build:
      context: ./dpppt-backend-sdk/dpppt-backend-sdk-ws/target/docker
      dockerfile: Dockerfile
    image: dpppt:backend
    environment:
      TZ: Europe/Madrid
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/dpppt
      DATASOURCE_USER: dpppt
      DATASOURCE_PASS: dpppt
      DATASOURCE_SCHEMA: public
      DATASOURCE_FLYWAY_LOAD: 'false'
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      service:

  postgres:
    image: postgres:12-alpine
    environment:
      TZ: Europe/Madrid
      POSTGRES_DB: dpppt
      POSTGRES_USER: dpppt
      POSTGRES_PASSWORD: dpppt
      POSTGRES_SCHEMA: dpppt
    volumes:
      - ./dpppt-backend-sdk/dpppt-backend-sdk-data/src/main/resources/db/migration/pgsql:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      service:
        aliases:
          - postgres

networks:
  service:
