### getOffer
POST {{baseUrl}}/v1/gaen/exposed
Content-Type: application/json
User-Agent: test
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjUtUnFxVFRZb21mcFZ6MDZWUkVPZnJiY3FhNVd1MmRfWDgydl9aVE0tVlUifQ.eyJqdGkiOiI4ZmE5MWRlMi03YmYwLTRhNmYtOWIzZC1hNzdiZDM3ZDdiMTMiLCJleHAiOjE1ODczMTYzMTgsIm5iZiI6MCwiaWF0IjoxNjE2NTMzNTA3LCJpc3MiOiJodHRwczovL2lkZW50aXR5LXIuYml0LmFkbWluLmNoL3JlYWxtcy9iYWctcHRzIiwic3ViIjoiMWVmYTliZWYtOWU5ZC00MjNjLTkxMjctZmQwYjAxNWQxOTY2IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicHRhLWFwcC1iYWNrZW5kIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiZGVjYzQ3Y2YtMmUyZi00NjZlLThiNTAtZmQ4MTAzZmQ4ZDNhIiwiYWNyIjoiMSIsInNjb3BlIjoiZXhwb3NlZCIsIm9uc2V0IjoiMjAyMC0wNS0yNSJ9.mybSSUal5Pc8q4nxy14co5dsxNTSfKpaTo-ZQo2Qn1EdS6h0wrdyQL5pE2cwc1hmI4gf-vG8rU9e5qg8nOvWPA

{
  "key": "123456789123",
  "onset": "2021-03-23"
}

###

GET {{baseUrl}}/v1/gaen/exposed/22-04-2020
Content-Type: application/protobuf
User-Agent: test

###
